version: "2"
services:
  database:
    image: postgres:9.6.1
    restart: always
    env_file:
      - dev.env
    volumes:
      - database:/var/lib/postgresql/data

  app:
    image: registry.gitlab.propulsion-home.ch/wilsz2rt/django-social-api:latest
    restart: always
    env_file:
      - dev.env
    ports:
      - "8050:8000"
      - "4738:22"
    command: "/usr/sbin/sshd -D"
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./app:/app
      - ./media-files:/media-files
      - ./static-files:/static-files
      - ./scripts:/scripts

volumes:
  database:
