version: "3"
services:

  app:
    image: registry.gitlab.propulsion-home.ch/wilsz2rt/django-social-api:latest
    restart: always
    ports:
      - "8080:8000"
      - "4738:22"
    command: "/usr/sbin/sshd -D"
    volumes:
      - ./app:/app
      - ./media-files:/media-files
      - ./static-files:/static-files
      - ./scripts:/scripts
#    depends_on:
#      - database
#
#volumes:
#  database:
