version: '2'
services:
  database:
    image: postgres:9.6.1
    restart: always
    env_file:
      - prod.env
    volumes:
      - database:/var/lib/postgresql/data


  app:
    image: registry.gitlab.propulsion-home.ch/wilsz2rt/django-social-api:latest
    restart: always
    env_file:
      - prod.env
    depends_on:
      - database
    command: 'sh /scripts/run.sh'
    ports:
      - "80:8000"
    volumes:
      - run:/run
      - static-files:/static-files
      - media-files:/media-files

  nginx:
    image: nginx:latest
    volumes:
      - run:/run
      - static-files:/static-files
      - media-files:/media-files
      - ./nginx:/etc/nginx/conf.d
    ports:
    - "80:80"
    command : /bin/bash -c "nginx -g 'daemon off;'"

volumes:
  database:
  static-files:
  media-files:
  run:
