# Generated by Django 2.0.3 on 2018-03-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='post content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='post created')),
            ],
        ),
    ]
