# Generated by Django 2.0.3 on 2018-03-29 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0009_friendrequests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequests',
            options={'verbose_name': 'FriendRequest', 'verbose_name_plural': 'FriendRequests'},
        ),
        migrations.AlterField(
            model_name='friendrequests',
            name='request_status',
            field=models.CharField(choices=[('open', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='open', max_length=20, verbose_name='request status'),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequests',
            unique_together={('request_from', 'request_to')},
        ),
    ]
