# Generated by Django 2.0.3 on 2018-03-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20180330_0713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
