# Generated by Django 2.0.3 on 2018-03-30 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0012_auto_20180330_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='shared'),
        ),
    ]
