# Generated by Django 2.0.3 on 2018-03-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_post_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(null=True, to='feed.Tag', verbose_name='tags'),
        ),
    ]
