# Generated by Django 2.0.3 on 2018-03-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_auto_20180330_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='feed.Tag', verbose_name='tags'),
        ),
    ]
