# Generated by Django 2.0.3 on 2018-03-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20180330_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='feed.Post', verbose_name='shared'),
        ),
    ]
